### ISSUE TITLE
Installation instructions shouldn't need to add ntwitter & underscore dependencies

### ISSUE THREAD

**Issue by technicalpickles** [chamerling/hubot-twitterstream-script#1]
> Add ntwitter and underscore dependencies in Hubot as defined in the documentation : Add to package.json then run 'npm install'

Since this is released as an npm module, you should be able to define your dependencies in this projects package.json, and user's just need to add `hubot-twitterstream-script` to their package.json and external-scripts.json.

**Comment by neufeldtech** [comment]
Installation instructions were updated in #4

**Comment by chamerling** [comment]
Thx @neufeldtech
